import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";
const inter = Inter({ subsets: ["latin"] });
// const client = new ApolloClient({
//   uri: "https://example.com",
//   cache: new InMemoryCache(),
// });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ApolloProvider client={client}>    {/* </ApolloProvider> */}
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>

  );
}
